export const REQUESTED_TOP_STORIES = 'app/HackerNews/REQUESTED_TOP_STORIES'
export const RECEIVED_TOP_STORIES = 'app/HackerNews/RECEIVED_TOP_STORIES'
export const RECEIVED_LAST_TOP_STORIES = 'app/HackerNews/RECEIVED_LAST_TOP_STORIES'
export const FAILED_TOP_STORIES = 'app/HackerNews/FAILED_TOP_STORIES'
